import { siteAudit, type SiteAudit } from "./siteaudit.js";
import type { Finding, Severity } from "./diagnose.js";

/**
 * Format a site_audit into a shareable Markdown report (for founders, devs, or
 * clients) — the crawl's findings, triaged and with fix snippets, as one
 * copy-paste document. Backed by siteAudit(); run crawl_site first.
 */

const SEV_ICON: Record<Severity, string> = { critical: "🔴", warning: "🟡", info: "⚪", good: "🟢" };

export function siteAuditReport(siteUrl: string): { markdown: string; audit: SiteAudit } {
  const a = siteAudit(siteUrl);
  const L: string[] = [];
  L.push(`# Technical SEO report — ${a.siteUrl}`, "");

  if (a.crawledPages === 0) {
    L.push(a.headline);
    return { markdown: L.join("\n"), audit: a };
  }

  L.push(`**Grade ${a.grade} · ${a.score}/100.** ${a.headline}`, "");
  L.push(
    "| Metric | Value |",
    "| --- | --- |",
    `| Pages crawled | ${a.metrics.total} |`,
    `| Indexable | ${a.metrics.indexable} |`,
    `| Noindex | ${a.metrics.noindex} |`,
    `| Redirected | ${a.metrics.redirected} |`,
    `| Broken (4xx/5xx) | ${a.metrics.broken} |`,
    `| Orphaned | ${a.metrics.orphans} |`,
    `| Internal links | ${a.graph.edges} across ${a.graph.nodes} pages |`,
    ""
  );

  const groups: [string, Severity][] = [
    ["Fix now", "critical"],
    ["Worth improving", "warning"],
    ["Minor / FYI", "info"],
  ];
  for (const [label, sev] of groups) {
    const items = a.findings.filter((f: Finding) => f.severity === sev);
    if (!items.length) continue;
    L.push(`## ${label}`, "");
    for (const f of items) {
      L.push(`### ${SEV_ICON[f.severity]} ${f.title}`);
      L.push(f.why);
      L.push(`**What to do:** ${f.whatToDo}`);
      if (f.fix) L.push("```", f.fix, "```");
      if (f.sampleUrls?.length) L.push(`Examples: ${f.sampleUrls.slice(0, 5).map((u) => `\`${u}\``).join(", ")}`);
      L.push("");
    }
  }

  L.push("---", `_Generated by Searchlight from a direct crawl of ${a.metrics.total} pages._`);
  return { markdown: L.join("\n"), audit: a };
}
